development:
  access_key_id: AKIAJND7ZUXZCY2GBUGQ
  secret_access_key: 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
  
production:
  access_key_id: AKIAJND7ZUXZCY2GBUGQ
  secret_access_key: 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

test:
  access_key_id: AKIAJND7ZUXZCY2GBUGQ
  secret_access_key: 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